version: '3.8'

services:

  libcam:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mredig/libcamera-streamer:latest
    restart: unless-stopped
    privileged: true
    volumes:
      - /run/udev/:/run/udev:ro
      - /mnt/ramdisk:/mnt/ramdisk

  lanweb:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - /mnt/ramdisk:/usr/share/nginx/html
    ports:
      - 8080:80
